### ISSUE TITLE
Corrupted Shaders.

### ISSUE THREAD

**Issue by zameran** [LGhassen/Scatterer#10]
Can you privide full code of shaders? 
That uncomliled shaders, that u always commting is corupted. 
Realy. Opensource to Opensource.
Thx.

**Comment by LGhassen** [comment]
Which shader are you talking about? How are they corrupted? Everything works fine, are you using unity 4 to compile them?

**Comment by zameran** [comment]
Yah, Unity 4.
Your compiled shaders work's fine in KSP and other application, if load this compiled shaders externaly. 
But a lot of 'source' shaders won't work as indeed.
E.g ocean shaders and atmosphere postprocess.
E.g all atmo postprocess code provide nothing - transparent postprocess cube in any case.

P.s i can upload my sources. But i think you have no time to deal with my version of your mod :)

**Comment by LGhassen** [comment]
Indeed I can't, however you have to be more precise. The postprocessing shader needs a depth buffer to work, and I made several variants that work off different types of depth buffer, there is also code in there to generate 24bit depth buffer on dx11/opengl or a logarithmic buffer and the postprocessing shader has to account for that. Also the postprocessing and ocean shaders have include files, which have their own parameters, and they need the precomputed atmospheric scattering tables passed as textures. Also, keep I mind there may be obsolete shader files I keep here because there are some interesting bits in them I may need later on.

What are you trying to achieve exactly? What did you change in your version? And please don't flag this as an issue if it isn't an actual issue with the what the mod does or how it works.

**Comment by zameran** [comment]
So. Before that day i think that uncompiled version of shaders is some sort of "working copy", and it is broken.

This is not an issue - this is step to not contact you on forums.
Thank, you, i will see what i can do - now i know that uncompiled version of shaders is good, and working variants.

Glad.
