### ISSUE TITLE
Wierd "Lines" in ocean texture

### ISSUE THREAD

**Issue by AstroWindh** [LGhassen/Scatterer#101]
KSP: 1.9.1 Windows 10 64bit
Problem: Wierd lines in ocean at certain camera angles.

Mods installed:

Scatterer 0.0610

EnvironmentalVisualEnhancements
Distant Object
Kerbal Engineer
MechJeb 2
NavyFish Docking port alignment indicator
PlanetShine
PoodsSkyboxes
ReStock
StockVisualEnhancements 1.0.8
TextureReplacer
TriggerTech Kerbal Alarm Clock

Reproduction steps:

With ocean shaders enabled, default scatterer settings: Launch a ship from KSP, look at ocean, at certain angles darker blue (non shaded?) lines appear, up to about end of atmosphere. 
[output_log.txt](https://github.com/LGhassen/Scatterer/files/4772748/output_log.txt)

Log: https://www.dropbox.com/s/6ivouzizb5en290/output_log.txt?dl=0

**Comment by LGhassen** [comment]
This appears to be an issue with ocean shadows. These is on an old version of KSP and an old version of scatterer.

I overhauled the ocean shadows recently and fixed some bugs on them, so try the latest version (requires KSP 1.8 or 1.9).

If you want to stay on the old KSP version you can just disable ocean shadows (there is an option in the scatterer menu in KSC scene). Pretty sure this should be fixed in the latest version though.

I will close the issue, but you can reopen it if it persists on the latest version.
