### ISSUE TITLE
Update source code

### ISSUE THREAD

**Issue by Tuupertunut** [LGhassen/Scatterer#146]
I noticed that the source code is still in version 0.772. Could we get the source for the latest versions pushed into github?

**Comment by LGhassen** [comment]
Hi, there are some parts of the new source code that I want to use for a commercial project, and therefore don't want this source to be public, as I feel it would undermine that project.

**Comment by Tuupertunut** [comment]
In that case I think you need to change the license from GPL to a closed license (and check that none of the libraries you use have GPL). It would be nice to have at least most of the code available though 🙂

One thing you could do would be to package the closed code in a library and call that from an open source mod.

**Comment by LGhassen** [comment]
That feels too much like work for my hobby project 😅

**Comment by R-T-B** [comment]
Changing the license to an all rights ressrved would be easy if it were not for the forum rules.

I'd suggest a hybrid license in the license docs.  Version <=0.772 are GPL, everything else ARR.

Just don't mention on the forums maybe.  I personally understand the desire to keep some code private...  your choice.

**Comment by Tuupertunut** [comment]
Just to be clear, this means that if you ever become inactive, there is no way anyone could continue updating Scatterer, like people have traditionally done with many other KSP mods. Also some users like me like to see how the code works and help debugging issues we find. But yeah, if you understand this, go ahead and change the license to All Rights Reserved.

**Comment by R-T-B** [comment]
> Just to be clear, this means that if you ever become inactive, there is no way anyone could continue updating Scatterer, like people have traditionally done with many other KSP mods. Also some users like me like to see how the code works and help debugging issues we find. But yeah, if you understand this, go ahead and change the license to All Rights Reserved.

Partially true.  I'm sure the community would pick up from the 0.772 sources, but yes, it would be quite a loss.

**Comment by R-T-B** [comment]
The only thing licensed under GPL is the release up to 0.772.  The release archives contain no license, and there is no source with which could imply a license, so...

Furthermore there couldn't be any contributors but @LGhassen after 0.772 since the source has not been expressly available.  It just isn't logical to think there would be.

But you are still mostly right.  There have been contributors in the past (I should know, I was one, a lot of the unified camera logic was mine) and their work may exist in the newer binaries, in which case, without their permission he can't legally execute a license change.  The only way to do that would be one the following options:

1.)  Get all past code contributors permission to use their code in an ARR context.  You can see a list of contributors at the github page.  I'll start you off with mine, I honestly don't care and this is more your baby from my perspective.

2.)  You could also reimplement any contributed pull requests or commits in such a way that the original authors work is no longer present.

3.) Make the closed source part a seperate binary that the open source portion calls.

or 4.) Just make the dang thing GPL.

I don't care, it's up to you man.  Just warning you it is a bit of a minefield legally speaking.

**Comment by LGhassen** [comment]
I have not decided what to do yet. I will take down the versions in violation of GPL until then.

**Comment by R-T-B** [comment]
> I have not decided what to do yet. I will take down the versions in violation of GPL until then.

I'm appreciative that you take this seriously.  If you want/desire my thoughts on this, just look at past PR's and commits you accepted, and be certain you have changed how they work just enough to be a unique work.  It's really not more tricky than that.

**Comment by jmburbach** [comment]
The binaries are hosted on the same project page which states the project is GPL so it's a bit implied, but your right, the releases don't explicitly have a license included. However unless they are in no way built upon the previous work they are not immune to the GPL. 

Anyway as I said I have no real dog in the fight and I don't wish to make trouble for you or start an argument. So let me just say thank you to all those involved in the project (which I've enjoyed immensely) and will trust you to do whatever you feel is right.and in the spirit of the license/project/community.

**Comment by R-T-B** [comment]
> The binaries are hosted on the same project page which states the project is GPL so it's a bit implied, but your right, the releases don't explicitly have a license included. However unless they are in no way built upon the previous work they are not immune to the GPL.
> 
> Anyway as I said I have no real dog in the fight and I don't wish to make trouble for you or start an argument. So let me just say thank you to all those involved in the project (which I've enjoyed immensely) and will trust you to do whatever you feel is right.and in the spirit of the license/project/community.

I agree completely, it's semantics anyways re the how the license is distributed.

We all just want a good quality scatterer, and are happy to wait while @LGHassen gets it figured out, I am sure.

**Comment by Alex6511** [comment]
Just to be clear, even if he were to re-write the shared contributions, the entire work is protected by GPL. GPL requires all modifications to be licensed under GPL or a compatible license. This means that the modifications to remove the other people's work would still be protected. The only way to go remove the GPL license would be to go back to a commit from before it was implemented. There does exist some work around to GNU General Public License v3.0, which is why a lot of open source projects use GNU Affero General Public License v3.0 now (which is a compatible license, so it is one you could convert to) but the reality is that the license is essentially designed to not allow you to make the work closed source retroactively. Once you go open source, there is supposed to be no going back.

**Comment by LGhassen** [comment]
This kind of discussion completely kills my enthusiasm about working on this

**Comment by Alex6511** [comment]
GPL allows for commercial use, why not just use it commercially and continue to maintain the repo?

**Comment by LGhassen** [comment]
Plugin source is updated (GPL 3).
Newest shaders source are not public but they are distributed in assetbundle form under CC BY-NC-ND 4.0. They are loaded dynamically and are not necessary to build the plugin, they can be replaced by custom shaders.
