### ISSUE TITLE
TAA broken with TUFX

### ISSUE THREAD

**Issue by LGhassen** [LGhassen/Scatterer#157]
https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip19x-112x-scatterer-atmospheric-scattering-00831-01022022-scattering-improvements-in-game-atmo-generation-and-multi-sun-support/&do=findComment&comment=4104674

**Comment by LGhassen** [comment]
Fix in 0.0834

**Comment by LGhassen** [comment]
Reportedly still broken in map view

**Comment by JonnyOThan** [comment]
I'm not quite understanding the bug that was reported here.  If AA is disabled in TUFX, does it still affect scatterer?  Because I'm pretty sure the reverse IS true: if TAA is disabled in scatterer, it disables TUFX's antialiasing setting.

I prefer TUFX for TAA for 2 reasons: it looks better than scatterer's version and it doesn't jitter the UI.  But the problem is that it seems to be disabled every time I switch back from map mode if I disable TAA in scatterer.

Is TAA actually an important part of how scatterer works, or is it just supposed to improve the graphics quality?  If the latter, would it be crazy to remove it and just recommend using TUFX instead?  If scatterer can't work with any other kind of AA then it could always forcibly disable them when detected or pop up warnings or whatever.

**Comment by LGhassen** [comment]
"Reportedly still broken in map view", it's broken regardless of scatterer having TAA or not, it's that simple.

**Comment by JonnyOThan** [comment]
Huh, someone pointed out to me that TUFX’s problem with persisting AA settings is a known issue and not related to scatterer.  I was pretty sure I tested without scatterer installed at all but I must have missed something.  Sorry about that :(

**Comment by LGhassen** [comment]
The original issue should be fixed
