### ISSUE TITLE
ReferenceEquals not working for null

### ISSUE THREAD

**Issue by linuxgurugamer** [LGhassen/Scatterer#165]
In ScreenCopyCommandBuffer.cs, in the OnDestroy() method, the following is not working:

`			if (!ReferenceEquals(targetCamera,null))
			{
`

I added a debug statement, and saw it appear in my log file:

`			if (!ReferenceEquals(targetCamera,null))
			{
				if (targetCamera == null)
					Debug.Log("ScreenCopyCommandBuffer, targetCamera is null");
`

Log snippit:
`161114 ScreenCopyCommandBuffer, targetCamera is null 
161117 Uploading Crash Report
161118 NullReferenceException
161119   at (wrapper managed-to-native) UnityEngine.Camera.RemoveCommandBufferImpl(UnityEngine.Camera,UnityEngine.Rendering.CameraEvent,UnityEngine.Rendering.CommandBuffer)
161120   at UnityEngine.Camera.RemoveCommandBuffer (UnityEngine.Rendering.CameraEvent evt, UnityEngine.Rendering.CommandBuffer buffer) [0x0003c] in <12e76cd50cc64cf19e759e981cb725af>:0 
161121   at scatterer.ScreenCopyCommandBuffer.OnDestroy () [0x0003a] in <52fb82aa69e44e32beb2cfb6a8bc4edc>:0 
`

KSP 1.12.3, full log file attached
[PlayerLog.zip](https://github.com/LGhassen/Scatterer/files/8988431/PlayerLog.zip)

**Comment by linuxgurugamer** [comment]
I found the same issue in SkySphereContainer.Cleanup()

**Comment by R-T-B** [comment]
I noticed this as well but did not think much of it.  At any rate, I'm told blackrack is currently under-the-weather and not coding for a bit.  Just FYI.

**Comment by gotmachine** [comment]
Using `ReferenceEquals()` on `UnityEngine.Object` derivatives can indeed induce unexpected behavior. It is perfectly fine to use on other classes.

To expand a bit, when doing `== null` or `Equals(null)` with an `UnityEngine.Object` derivative, what is actually checked is "is the reference null **or** is the underlying unity object destroyed". Depending on the code intent, it can be valid to perform a `ReferenceEquals(unityObject, null)`, as that will **only** check for "is that reference null", which can be desired in some cases.

This being said, I agree that in the specific case you highlighted, an `is the object null or destroyed` check is probably what should be done.

**Comment by linuxgurugamer** [comment]
@gotmachine Thank you for the explanation.

What I'm doing is monitoring the log file, and on a local copy of Scatterer, fixing the specific places where this error is occurring.  I'll do a PR in a week or so once I'm satisfied that I've found all the annoying locations.

I don't understand the codebase at all (without spending time on it), so am very reluctant to just blindly go and replace them if I don't see an error.  That being said, I'm sure there are other places where it should be replaced

**Comment by LGhassen** [comment]
@linuxgurugamer I'm not sure why I ever went with ReferenceEquals but from memory some objects were returning appearing as null when checking them with !=null despite not being null or destroyed, whereas with referenceEquals it was working.

Can't remember the specifics and have been putting referenceEquals everywhere since. You might as well replace them all and see if the mod still works.

Thanks for looking into this and preparing a PR.

**Comment by LGhassen** [comment]
@linuxgurugamer I'm curious if you ever experimented with this further or prepared a PR? If not no worries, and thanks for the report.

**Comment by linuxgurugamer** [comment]
Yes, I have a number of changes, I'll do a PR for you

**Comment by LGhassen** [comment]
Looks good, I will keep an eye out for any side effects and think about replacing the rest given the explanation by @gotmachine .

**Comment by LGhassen** [comment]
@gotmachine If I just create a monobehaviour with the a without adding it to a gameObject, then when doing `== null` it always returns a null, is this the expected behaviour? I guess a monoBehaviour is always supposed to be added as a component to a gameObject?

Anyway I guess this is where I started using ReferenceEquals for some things.

**Comment by gotmachine** [comment]
Yeah, you can't instantiate a MonoBehaviour, it must be added though AddComponent().

The thing to keep in mind is that all Unity C# objects are wrappers over a C++ object.
There is no common convention about how to create Unity objects from code. Many of them can be created through a C# constructor, for example GameObject or Texture2D, but some like MonoBehaviour are using other patterns like AddComponent().

But technically, there is indeed nothing preventing you from instantiating a MonoBehaviour, because there is always a default constructor for any C# class. Although to be true, if you were to run that constructor from the Unity editor or in modified KSP install using the development runtime (for debugging/profiling), you would get an error message in the log.

If you use the MonoBehaviour constructor (but you really shouldn't), you get the C# "shell", but not the associated C++ object. Essentially, you get a "pre-destroyed" instance. This mean that calling all Unity API methods that are forwarded to C++ calls will fail, and a `== null` call will return true accordingly.

If you really need an object whose lifecycle is independent from the Unity/KSP objects lifecycle, then just make a regular C# class that doesn't inherit from MonoBehaviour, and have another MonoBehaviour class that acquire/consume a reference to that object. But in my experience, such a pattern can usually be avoided easily.

**Comment by LGhassen** [comment]
Thanks a lot for the explanation.
