### ISSUE TITLE
CPU Bottleneck on title screen with Scatterer 0.0838

### ISSUE THREAD

**Issue by TrilatGames** [LGhassen/Scatterer#191]
KSP:

1.12
Ubuntu 22.04
Quad Core CPU 1GHZ

Problem:

Strong CPU Bottleneck on newest version of Scatterer

Mods installed:

Scatterer 3:v0.0838

Reproduction steps:

Install it on a lower power Gaming Machine with Lower Power Quad Core CPU. now run the game and it will be frozen at 0fps on the title screen!

**Comment by LGhassen** [comment]
Better check your logs

**Comment by TrilatGames** [comment]
> I don't think that's a strong cpu bottleneck, I think you don't have a GPU.
> 
> Download and replace your .dll with this https://www80.zippyshare.com/v/WfABq3zD/file.html then add this to the main settings file `useLowResolutionAtmosphere = true`
> 
> If it doesn't work post logs

Unfortunately, those edits didn't work! It still Crashes.

Logs from before and after the edits are available at http://drive.google.com/drive/folders/1yzfQBHpqnl7CAb_2NDDllC2OeprawVIJ.

**Comment by LGhassen** [comment]
Ok so you do have a GPU. There is nothing in the log to explain the crash.

However seeing as you're on ubuntu and running opengl, can you try to run it with Vulkan using proton or dxvk?

**Comment by BonsaiDen** [comment]
Running into the same issue here, in fact it's so bad it nearly freezes the compositor making it difficult to actually close the game :D

Rig: Ryzen 2700X 8 Core / NVIDIA GTX 2070 Super.

Also tried the custom DLL with the config parameter - sadly without effect :/

The Logs are just as empty as Trilat's ones when it comes to giving any clues about what is going on.

I did use Proton to run the Windows Version in the past, but ever since that dreaded launcher got patched in I haven't been able to get it running under proton (launcher loading screen pops up, disappears and the game itself doesn't launch).

**Comment by E3FxGaming** [comment]
Not sure about it being a CPU bottleneck, but I'm experiencing the same symptoms (main menu freezing and game hard to close) on Linux.

KSP 1.12.5.3190 (LinuxPlayer)

Manjaro Linux XFCE
Intel i7-4770k / Nvidia GTX 1080 Ti

No relevant info in the log

**Comment by Danny2two** [comment]
I found a way to get the game running with Scatterer. Target the game "KSP_X64.exe" with Lutris and run it as a windows exe. Skips the stupid new launcher and the game runs okay. I have seen the game hang in the settings menu for some reason. 

Im on Manjaro GNOME
Ryzen 3700x 
RTX 3070Ti

**Comment by LGhassen** [comment]
Try with the latest version.
