### ISSUE TITLE
Orbital Map issue when landed on Kerbin

### ISSUE THREAD

**Issue by zenmetsu** [LGhassen/Scatterer#23]
I have noticed that when the map is viewed from a craft landed on Kerbin, the entire planet is drawn as ocean.  Worse yet, the ocean appears to be drawn in front of most other items such as orbit lines.  The issue is not present from orbital craft, nor is it a problem from the tracking station.  The issue is resolved when scatterer is disabled.

Is this a configuration problem, or is something else wrong?  I have a video demonstrating the issue if need be.

**Comment by zenmetsu** [comment]
![screenshot58](https://cloud.githubusercontent.com/assets/6358379/21351894/3b2665a4-c67c-11e6-86d2-6ca11ea4e487.png)

**Comment by LGhassen** [comment]
I have never seen this before, could you give me all information, what version and video mode you are running, as well as your output.log file (after the issue happened). Send me that video also.

**Comment by zenmetsu** [comment]
Sure, I'll push the requested files up once I get home from the office.  I was using 0.0270 version of Scatterer.  As for configs, I was using the StockVisualEnhancements config as provided by CKAN.  Is there a default config set somewhere that I can test with?

**Comment by TwistedMinds2** [comment]
A similar issue happened to me while using scatterer 0.0300 with RSSVE. There was a sporadic discussion about it in the thread, starting around [[here](http://forum.kerbalspaceprogram.com/index.php?/topic/153511-122-real-solar-system-visual-enhancements-v122-rc3-2017-02-26/&do=findComment&comment=2969478)]. Fortunately, a [[fix](http://forum.kerbalspaceprogram.com/index.php?/topic/153511-122-real-solar-system-visual-enhancements-v122-rc3-2017-02-26/&do=findComment&comment=2978157)] was found. I've been using it since it was found and without side effects (that I am aware of, at least).

The fix is to change a line (Rt = 6511000) in Earth_Atmosphere.cfg to (Rt = 6461153.5). Of course the file and value will be different for the default scatterer config/solar system but hopefully it can point you in the correct direction :)

**Comment by LGhassen** [comment]
Should be fixed now
